### ISSUE TITLE
App crashes when I click on the "new reminder" button

### ISSUE THREAD

**Issue by eksynn** [Stefangansevles/RemindMe#1]
The error says:
"RemindMe has stopped working

A problem caused the program to stop working correctly.
Windows will close the program and notify you if a solution is
available."

Followed by a "Close program" button on the lower right.

**Comment by Stefangansevles** [comment]
That is just the default windows error from what i can see. 

What version are you running?
Did you do anything before you pressed the button?

Try going to C:\Users\your_name\AppData\Local\RemindMe\ErrorLog.txt
does it contain anything?

if not, 
Try going to C:\Users\your_name\AppData\Local\Temp\RemindMe\SystemLog.txt
Can you post the contents of this?

**Comment by eksynn** [comment]
the latest version, as of 6 days ago
i opened it, then went straight to the button. nothing else besides that

the first folder has 3 files, none of which are ErrorLog.txt
install.bat, RemindMeDatabase.db, and string.txt

the second folder doesn't exist

**Comment by Stefangansevles** [comment]
That's really weird.. There's no particular code that could make the app crash to my knowing

I'm assuming you have these files:
![](https://user-images.githubusercontent.com/25766371/75913892-12915680-5e54-11ea-9c4f-526fe9c1581e.png)
 in C:\Users\you\AppData\Local\RemindMe\Application

other than that, im not sure what could cause this issue
