### ISSUE TITLE
Disable popups 

### ISSUE THREAD

**Issue by vrfebet** [Stefangansevles/RemindMe#13]
I use the program as a school bell at home for individual teaching children's , so I only need sound as output. Is it possible to add a button to suppress all popups to alert only sound?
I didn't find such a setting.

**Comment by Stefangansevles** [comment]
There is an option in the settings. You can set the Popup Type to Minimized. This way you will hear the sound, and don't see the popup, but it will be visible in your taskbar.

I might add another option for sound only!

**Comment by vrfebet** [comment]
Thank you for your reaction! It would be good to add another option for sound only. After a few hours notice, the main taskbar is filled with flashing panels...

**Comment by Stefangansevles** [comment]
Feature added in V3.1.08 :)

**Comment by Stefangansevles** [comment]
If you encounter any issues be sure to let me know

**Comment by vrfebet** [comment]
Of course.
I'll try it tomorrow morning.
Is it possible to log event logging into the file?

**Comment by Stefangansevles** [comment]
What do you mean by "Is it possible to logging event into the file?" ?

**Comment by vrfebet** [comment]
debug log

**Comment by Stefangansevles** [comment]
yes, %localappdata%\Temp\RemindMe

**Comment by vrfebet** [comment]
Hi,
popping suppression works excellently, just again the program crashed on the background run.
Last row logs are the same and repeated 35 times:
[20.9.2021 16:15:59]  Pinging online status
[20.9.2021 16:15:59]  Updating user
[20.9.2021 16:15:59]  Invalid uniqueString version string parameter in BLOnlineDatabase.InsertUser(). String:
Nothing about falling...
