### ISSUE TITLE
Concept: Sync with mobile

### ISSUE THREAD

**Issue by BrandonKMLee** [Stefangansevles/RemindMe#7]
**Is your feature request related to a problem? Please describe.**
RemindMe is PC only, and most people will have an Android/iOS app for on-the-move reminders.

**Describe the solution you'd like**
Possibly a sync function or API between mobile applications and ReMindMe

**Additional context**
https://github.com/HossamElghamry/Mediminder
https://github.com/brains-and-beards/flutter-reminders-app

**Comment by Stefangansevles** [comment]
I have actually thought about this before, but it's quite a large undertaking. Thanks for the suggestion though!
