### ISSUE TITLE
Colon in filename messes up `git clone` on Windows

### ISSUE THREAD

**Issue by LoganDark** [Stefangansevles/RemindMe#8]
**Describe the bug**
Windows NT has a bug where filenames cannot contain `:`

**To Reproduce**
Run `git clone` on Windows instead of WSL

**Expected behavior**
Filenames do not contain colons

**Screenshots**
![image](https://user-images.githubusercontent.com/4723091/125543599-2920c109-9d48-49fb-9882-991d9da42167.png)

**Additional context**
This can easily be worked around by using WSL (Windows Subsystem For Linux)

I am pretty sure only WSL 1 will work as the others just run in a virtual machine.

![image](https://user-images.githubusercontent.com/4723091/125543642-e7b00263-9bcd-4095-9809-be3d58be8938.png)

As you can see the colons here are invalid characters:

![image](https://user-images.githubusercontent.com/4723091/125543718-048ef212-0e8a-4c82-b15e-2dba88f3d207.png)

Even though WSL can read them correctly, Windows has a fit due to old and buggy legacy code

**Comment by Stefangansevles** [comment]
I've removed the colons, thanks for the heads up!
